### ISSUE TITLE
How do i specify the region 

### ISSUE THREAD

**Issue by saikrishna321** [kianhean/AWSBuildMonitor#2]

**Comment by kianhean** [comment]
Hi @saikrishna321 

in the readme i used 
```aws configure```
in one of steps they will ask for your region.

I am using boto3 under the hood.
http://boto3.readthedocs.io/en/latest/guide/configuration.html

enviroment variable might be easiest but there are other methods as highligted in the link

AWS_DEFAULT_REGION
The default region to use, e.g. us-west-1, us-west-2, etc.

**Comment by saikrishna321** [comment]
cheers .. that works :) thanks a lot
