### ISSUE TITLE
Build progress not showing progress 

### ISSUE THREAD

**Issue by saikrishna321** [kianhean/AWSBuildMonitor#3]
I can't get to see the % of the build status, like the one in readMe

<img width="194" alt="screen shot 2018-04-24 at 2 38 55 pm" src="https://user-images.githubusercontent.com/4045041/39190840-5c8b7ff8-47cd-11e8-88cd-63d52756cf99.png">

**Comment by kianhean** [comment]
Hi @saikrishna321 

yea i couldnt get that to work too

http://boto3.readthedocs.io/en/latest/reference/services/codepipeline.html#CodePipeline.Client.get_pipeline_state

boto3 states that it is a return from pipeline but it currently doesnt populate.
maybe we should raise it at the boto3 project. 

I might be doing something wrong

**Comment by kianhean** [comment]
No new discussion.
Closing Issue
