### ISSUE TITLE
Question: License

### ISSUE THREAD

**Issue by ghost** [kianhean/AWSBuildMonitor#5]
I just stumbled upon this repo and I was wondering what's the license status? can other people use this solution as well?

Thanks in advance.

**Comment by kianhean** [comment]
Hi

Have not explicitly put a license I will do that shortly.

Will keep it under Apache License 2.0 so you may use this solution as well :)

**Comment by ghost** [comment]
Thank you very much :)

**Comment by mario-castellanos** [comment]
Hi, we like the tool as well and it would be nice if you publish the license. Thx in advance :-)

**Comment by kianhean** [comment]
Thanks everyone I will definitely post that in the weekend

**Comment by kianhean** [comment]
Ok was easy to add via the website. Done!
